/* Auto-generated by generate_peripherals.py */
#ifndef UART_ADDRS_H
#define UART_ADDRS_H

#include <stdint.h>

typedef struct {
    const char* name;
    uint32_t data;
    uint32_t status;
    uint32_t ctrl;
} uart_hw_t;

static const uart_hw_t uart_hw_table[] = {
};

#endif
